# Generated by Django 3.2.6 on 2021-08-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(help_text='Created Datetime')),
                ('huminity', models.FloatField(help_text='Huminity')),
                ('temperature', models.FloatField(help_text='Temperature')),
                ('eCO2', models.IntegerField(help_text='eCO2')),
                ('TVOC', models.IntegerField(help_text='TVOC')),
            ],
        ),
    ]
